window.esdocSearchIndex = [
  [
    "medidoc/src/position.js~position",
    "class/src/Position.js~Position.html",
    "<span>Position</span> <span class=\"search-result-import-path\">medidoc/src/Position.js</span>",
    "class"
  ],
  [
    "medidoc/src/buffer.js~buffer",
    "function/index.html#static-function-buffer",
    "<span>buffer</span> <span class=\"search-result-import-path\">medidoc/src/buffer.js</span>",
    "function"
  ],
  [
    "medidoc/src/buffers.js~buffers",
    "function/index.html#static-function-buffers",
    "<span>buffers</span> <span class=\"search-result-import-path\">medidoc/src/buffers.js</span>",
    "function"
  ],
  [
    "medidoc/src/transform/visitor.js~extend",
    "function/index.html#static-function-extend",
    "<span>extend</span> <span class=\"search-result-import-path\">medidoc/src/transform/visitor.js</span>",
    "function"
  ],
  [
    "medidoc/src/transform/lib.js~iter",
    "function/index.html#static-function-iter",
    "<span>iter</span> <span class=\"search-result-import-path\">medidoc/src/transform/lib.js</span>",
    "function"
  ],
  [
    "medidoc/src/leaves.js~leaves",
    "function/index.html#static-function-leaves",
    "<span>leaves</span> <span class=\"search-result-import-path\">medidoc/src/leaves.js</span>",
    "function"
  ],
  [
    "medidoc/src/transform/lib.js~map",
    "function/index.html#static-function-map",
    "<span>map</span> <span class=\"search-result-import-path\">medidoc/src/transform/lib.js</span>",
    "function"
  ],
  [
    "medidoc/src/merge.js~merge",
    "function/index.html#static-function-merge",
    "<span>merge</span> <span class=\"search-result-import-path\">medidoc/src/merge.js</span>",
    "function"
  ],
  [
    "medidoc/src/transform/lib.js~next",
    "function/index.html#static-function-next",
    "<span>next</span> <span class=\"search-result-import-path\">medidoc/src/transform/lib.js</span>",
    "function"
  ],
  [
    "medidoc/src/parse.js~parse",
    "function/index.html#static-function-parse",
    "<span>parse</span> <span class=\"search-result-import-path\">medidoc/src/parse.js</span>",
    "function"
  ],
  [
    "medidoc/src/parsebundle.js~parsebundle",
    "function/index.html#static-function-parseBundle",
    "<span>parseBundle</span> <span class=\"search-result-import-path\">medidoc/src/parseBundle.js</span>",
    "function"
  ],
  [
    "medidoc/src/transform/simplify.js~simplify",
    "variable/index.html#static-variable-simplify",
    "<span>simplify</span> <span class=\"search-result-import-path\">medidoc/src/transform/simplify.js</span>",
    "variable"
  ],
  [
    "medidoc/src/split.js~split",
    "function/index.html#static-function-split",
    "<span>split</span> <span class=\"search-result-import-path\">medidoc/src/split.js</span>",
    "function"
  ],
  [
    "medidoc/src/stringify.js~stringify",
    "function/index.html#static-function-stringify",
    "<span>stringify</span> <span class=\"search-result-import-path\">medidoc/src/stringify.js</span>",
    "function"
  ],
  [
    "medidoc/src/stringifybundle.js~stringify",
    "function/index.html#static-function-stringify",
    "<span>stringify</span> <span class=\"search-result-import-path\">medidoc/src/stringifyBundle.js</span>",
    "function"
  ],
  [
    "medidoc/src/tokens.js~tokens",
    "function/index.html#static-function-tokens",
    "<span>tokens</span> <span class=\"search-result-import-path\">medidoc/src/tokens.js</span>",
    "function"
  ],
  [
    "medidoc/src/transform/visitor.js~visitor",
    "variable/index.html#static-variable-visitor",
    "<span>visitor</span> <span class=\"search-result-import-path\">medidoc/src/transform/visitor.js</span>",
    "variable"
  ],
  [
    "src/.external-ecmascript.js~array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array",
    "src/.external-ecmascript.js~Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~arraybuffer",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ArrayBuffer",
    "src/.external-ecmascript.js~ArrayBuffer",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~Boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~dataview",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/DataView",
    "src/.external-ecmascript.js~DataView",
    "external"
  ],
  [
    "src/.external-ecmascript.js~date",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date",
    "src/.external-ecmascript.js~Date",
    "external"
  ],
  [
    "src/.external-ecmascript.js~error",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error",
    "src/.external-ecmascript.js~Error",
    "external"
  ],
  [
    "src/.external-ecmascript.js~evalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/EvalError",
    "src/.external-ecmascript.js~EvalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float32Array",
    "src/.external-ecmascript.js~Float32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~float64array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Float64Array",
    "src/.external-ecmascript.js~Float64Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~Function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generator",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator",
    "src/.external-ecmascript.js~Generator",
    "external"
  ],
  [
    "src/.external-ecmascript.js~generatorfunction",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/GeneratorFunction",
    "src/.external-ecmascript.js~GeneratorFunction",
    "external"
  ],
  [
    "src/.external-ecmascript.js~infinity",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Infinity",
    "src/.external-ecmascript.js~Infinity",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int16Array",
    "src/.external-ecmascript.js~Int16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int32Array",
    "src/.external-ecmascript.js~Int32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~int8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Int8Array",
    "src/.external-ecmascript.js~Int8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~internalerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/InternalError",
    "src/.external-ecmascript.js~InternalError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~json",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/JSON",
    "src/.external-ecmascript.js~JSON",
    "external"
  ],
  [
    "src/.external-ecmascript.js~map",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map",
    "src/.external-ecmascript.js~Map",
    "external"
  ],
  [
    "src/.external-ecmascript.js~nan",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/NaN",
    "src/.external-ecmascript.js~NaN",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~Number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~Object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~promise",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Promise",
    "src/.external-ecmascript.js~Promise",
    "external"
  ],
  [
    "src/.external-ecmascript.js~proxy",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy",
    "src/.external-ecmascript.js~Proxy",
    "external"
  ],
  [
    "src/.external-ecmascript.js~rangeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RangeError",
    "src/.external-ecmascript.js~RangeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~referenceerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/ReferenceError",
    "src/.external-ecmascript.js~ReferenceError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~reflect",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Reflect",
    "src/.external-ecmascript.js~Reflect",
    "external"
  ],
  [
    "src/.external-ecmascript.js~regexp",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp",
    "src/.external-ecmascript.js~RegExp",
    "external"
  ],
  [
    "src/.external-ecmascript.js~set",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Set",
    "src/.external-ecmascript.js~Set",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~String",
    "external"
  ],
  [
    "src/.external-ecmascript.js~symbol",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Symbol",
    "src/.external-ecmascript.js~Symbol",
    "external"
  ],
  [
    "src/.external-ecmascript.js~syntaxerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/SyntaxError",
    "src/.external-ecmascript.js~SyntaxError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~typeerror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypeError",
    "src/.external-ecmascript.js~TypeError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~urierror",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError",
    "src/.external-ecmascript.js~URIError",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint16array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint16Array",
    "src/.external-ecmascript.js~Uint16Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint32array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint32Array",
    "src/.external-ecmascript.js~Uint32Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8array",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8Array",
    "src/.external-ecmascript.js~Uint8Array",
    "external"
  ],
  [
    "src/.external-ecmascript.js~uint8clampedarray",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Uint8ClampedArray",
    "src/.external-ecmascript.js~Uint8ClampedArray",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakmap",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakMap",
    "src/.external-ecmascript.js~WeakMap",
    "external"
  ],
  [
    "src/.external-ecmascript.js~weakset",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/WeakSet",
    "src/.external-ecmascript.js~WeakSet",
    "external"
  ],
  [
    "src/.external-ecmascript.js~boolean",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Boolean",
    "src/.external-ecmascript.js~boolean",
    "external"
  ],
  [
    "src/.external-ecmascript.js~function",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Function",
    "src/.external-ecmascript.js~function",
    "external"
  ],
  [
    "src/.external-ecmascript.js~null",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/null",
    "src/.external-ecmascript.js~null",
    "external"
  ],
  [
    "src/.external-ecmascript.js~number",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number",
    "src/.external-ecmascript.js~number",
    "external"
  ],
  [
    "src/.external-ecmascript.js~object",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object",
    "src/.external-ecmascript.js~object",
    "external"
  ],
  [
    "src/.external-ecmascript.js~string",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String",
    "src/.external-ecmascript.js~string",
    "external"
  ],
  [
    "src/.external-ecmascript.js~undefined",
    "https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/undefined",
    "src/.external-ecmascript.js~undefined",
    "external"
  ],
  [
    "src/position.js",
    "file/src/Position.js.html",
    "src/Position.js",
    "file"
  ],
  [
    "src/position.js~position#column",
    "class/src/Position.js~Position.html#instance-member-column",
    "src/Position.js~Position#column",
    "member"
  ],
  [
    "src/position.js~position#constructor",
    "class/src/Position.js~Position.html#instance-constructor-constructor",
    "src/Position.js~Position#constructor",
    "method"
  ],
  [
    "src/position.js~position#line",
    "class/src/Position.js~Position.html#instance-member-line",
    "src/Position.js~Position#line",
    "member"
  ],
  [
    "src/position.js~position#tostring",
    "class/src/Position.js~Position.html#instance-method-toString",
    "src/Position.js~Position#toString",
    "method"
  ],
  [
    "src/buffer.js",
    "file/src/buffer.js.html",
    "src/buffer.js",
    "file"
  ],
  [
    "src/buffers.js",
    "file/src/buffers.js.html",
    "src/buffers.js",
    "file"
  ],
  [
    "src/grammar.js",
    "file/src/grammar.js.html",
    "src/grammar.js",
    "file"
  ],
  [
    "src/index.js",
    "file/src/index.js.html",
    "src/index.js",
    "file"
  ],
  [
    "src/leaves.js",
    "file/src/leaves.js.html",
    "src/leaves.js",
    "file"
  ],
  [
    "src/merge.js",
    "file/src/merge.js.html",
    "src/merge.js",
    "file"
  ],
  [
    "src/parse.js",
    "file/src/parse.js.html",
    "src/parse.js",
    "file"
  ],
  [
    "src/parsebundle.js",
    "file/src/parseBundle.js.html",
    "src/parseBundle.js",
    "file"
  ],
  [
    "src/split.js",
    "file/src/split.js.html",
    "src/split.js",
    "file"
  ],
  [
    "src/stringify.js",
    "file/src/stringify.js.html",
    "src/stringify.js",
    "file"
  ],
  [
    "src/stringifybundle.js",
    "file/src/stringifyBundle.js.html",
    "src/stringifyBundle.js",
    "file"
  ],
  [
    "src/tokens.js",
    "file/src/tokens.js.html",
    "src/tokens.js",
    "file"
  ],
  [
    "src/transform/lib.js",
    "file/src/transform/lib.js.html",
    "src/transform/lib.js",
    "file"
  ],
  [
    "src/transform/simplify.js",
    "file/src/transform/simplify.js.html",
    "src/transform/simplify.js",
    "file"
  ],
  [
    "src/transform/visitor.js",
    "file/src/transform/visitor.js.html",
    "src/transform/visitor.js",
    "file"
  ]
]